name: Continuous Integration

on:
  push:
    branches-ignore:
      - "dependabot/**"
    paths-ignore:
      - ".gitignore"
      - "README.md"
      - "LICENSE"
      - "CHANGELOG.md"
      - "renovate.json"
      - ".husky/**"
  pull_request:
  workflow_dispatch:
  workflow_call:

env:
  GENERATE_SOURCEMAP: false

jobs:
  build-and-test:
    strategy:
      matrix:
        node-version: [ 18, 19 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    name: Build and Test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm i
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
